# Generated by Django 4.2.7 on 2025-08-06 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"]},
        ),
        migrations.AddField(
            model_name="user",
            name="ai_usage_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total AI interactions"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, help_text="Department or team", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_ai_interaction",
            field=models.DateTimeField(
                blank=True, help_text="Last AI service usage", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct manager or supervisor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User preferences for AI behavior, interface settings, and notifications",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("sales_manager", "Sales Manager"),
                    ("sales_rep", "Sales Representative"),
                    ("analyst", "Sales Analyst"),
                    ("viewer", "Viewer Only"),
                ],
                default="sales_rep",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="users_user_role_e1ec1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_login"], name="users_user_last_lo_5f84ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="users_user_created_cf865c_idx"
            ),
        ),
    ]
