# Generated by Django 4.2.7 on 2025-08-05 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meeting_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingsession",
            name="teams_conference_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="meetingsession",
            name="teams_join_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="meetingsession",
            name="teams_meeting_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="meetingsession",
            name="teams_meeting_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="meetingsession",
            name="teams_organizer_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="MicrosoftTeamsCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expiry", models.DateTimeField()),
                ("scope", models.TextField()),
                ("tenant_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Microsoft Teams Credentials",
                "verbose_name_plural": "Microsoft Teams Credentials",
            },
        ),
    ]
