# Generated by Django 4.2.7 on 2025-08-07 06:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0005_remove_opportunityintelligence_opportunity_and_more"),
        ("meeting_service", "0002_meetingsession_teams_conference_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Meeting title or subject", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Meeting description or notes"
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("discovery", "Discovery Call"),
                            ("demo", "Product Demo"),
                            ("proposal", "Proposal Presentation"),
                            ("negotiation", "Negotiation"),
                            ("closing", "Closing Call"),
                            ("follow_up", "Follow-up"),
                            ("other", "Other"),
                        ],
                        default="discovery",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(help_text="Scheduled meeting date and time"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Expected meeting duration in minutes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "agenda",
                    models.TextField(
                        blank=True, help_text="Meeting agenda and talking points"
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True, help_text="Meeting outcome and key takeaways"
                    ),
                ),
                (
                    "action_items",
                    models.JSONField(
                        default=list, help_text="Action items and follow-up tasks"
                    ),
                ),
                (
                    "ai_insights",
                    models.JSONField(
                        default=dict,
                        help_text="AI-generated insights and recommendations",
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(
                        blank=True, help_text="Meeting URL (Google Meet, Teams, etc.)"
                    ),
                ),
                (
                    "meeting_platform",
                    models.CharField(
                        blank=True, help_text="Meeting platform used", max_length=50
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(blank=True, help_text="Recording URL if available"),
                ),
                (
                    "participants",
                    models.JSONField(
                        default=list, help_text="List of meeting participants"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Actual meeting start time", null=True
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="Actual meeting end time", null=True
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="ai_service.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "status"], name="meeting_ser_lead_id_546d3a_idx"
                    ),
                    models.Index(
                        fields=["scheduled_at"], name="meeting_ser_schedul_ba57a2_idx"
                    ),
                    models.Index(
                        fields=["status"], name="meeting_ser_status_31098a_idx"
                    ),
                ],
            },
        ),
    ]
