# Generated by Django 5.2.4 on 2025-07-30 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_text', models.TextField()),
                ('extracted_data', models.JSONField(default=dict)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-analysis_timestamp'],
            },
        ),
    ]
