# Generated by Django 5.2.4 on 2025-07-31 17:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("company_size", models.CharField(blank=True, max_length=100)),
                (
                    "contact_info",
                    models.JSONField(
                        default=dict,
                        help_text="Contact details including name, email, phone, title, department",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="How this lead was acquired",
                        max_length=100,
                    ),
                ),
                (
                    "pain_points",
                    models.JSONField(
                        default=list, help_text="List of business challenges mentioned"
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        default=list,
                        help_text="List of specific needs or solutions requested",
                    ),
                ),
                (
                    "budget_info",
                    models.TextField(
                        blank=True,
                        help_text="Budget range, constraints, or approval process",
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True,
                        help_text="Project timeline or urgency",
                        max_length=255,
                    ),
                ),
                (
                    "decision_makers",
                    models.JSONField(
                        default=list, help_text="Names or roles of decision makers"
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "current_solution",
                    models.TextField(
                        blank=True, help_text="Existing tools or solutions mentioned"
                    ),
                ),
                (
                    "competitors_mentioned",
                    models.JSONField(
                        default=list,
                        help_text="Competitor names or alternatives discussed",
                    ),
                ),
                (
                    "crm_record_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in external CRM system",
                        max_length=255,
                    ),
                ),
                (
                    "crm_system",
                    models.CharField(
                        blank=True,
                        help_text="Which CRM system this syncs with",
                        max_length=50,
                    ),
                ),
                (
                    "conversation_history",
                    models.TextField(
                        blank=True, help_text="Original conversation transcript"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInsights",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lead_score",
                    models.FloatField(
                        default=0.0, help_text="Overall lead quality score (0-100)"
                    ),
                ),
                (
                    "conversion_probability",
                    models.FloatField(
                        default=0.0, help_text="Probability of conversion (0-100)"
                    ),
                ),
                (
                    "quality_tier",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "score_breakdown",
                    models.JSONField(
                        default=dict, help_text="Detailed scoring breakdown"
                    ),
                ),
                (
                    "estimated_deal_size",
                    models.CharField(
                        blank=True,
                        help_text="Predicted deal value range",
                        max_length=100,
                    ),
                ),
                (
                    "sales_cycle_prediction",
                    models.CharField(
                        blank=True,
                        help_text="Expected sales cycle duration",
                        max_length=100,
                    ),
                ),
                (
                    "key_strengths",
                    models.JSONField(default=list, help_text="Lead's key strengths"),
                ),
                (
                    "improvement_areas",
                    models.JSONField(
                        default=list, help_text="Areas needing more qualification"
                    ),
                ),
                (
                    "competitive_risk",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        default=list, help_text="AI-generated action recommendations"
                    ),
                ),
                (
                    "next_steps",
                    models.JSONField(default=list, help_text="Suggested next steps"),
                ),
                (
                    "next_best_action",
                    models.TextField(blank=True, help_text="Top priority action"),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        default=list, help_text="Potential risks identified"
                    ),
                ),
                (
                    "opportunities",
                    models.JSONField(
                        default=list, help_text="Opportunities identified"
                    ),
                ),
                (
                    "primary_strategy",
                    models.CharField(
                        blank=True,
                        help_text="Recommended sales approach",
                        max_length=50,
                    ),
                ),
                (
                    "key_messaging",
                    models.JSONField(
                        default=list, help_text="Recommended messaging points"
                    ),
                ),
                (
                    "objection_handling",
                    models.JSONField(
                        default=dict, help_text="Objection handling strategies"
                    ),
                ),
                (
                    "industry_insights",
                    models.JSONField(
                        default=dict, help_text="Industry-specific insights and trends"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, help_text="Confidence in AI analysis (0-100)"
                    ),
                ),
                (
                    "data_completeness",
                    models.FloatField(
                        default=0.0, help_text="Completeness of lead data (0-100)"
                    ),
                ),
                ("last_analyzed", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="ai_service.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Insights",
                "verbose_name_plural": "AI Insights",
                "ordering": ["-last_analyzed"],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["user", "status"], name="ai_service__user_id_c89d44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["company_name"], name="ai_service__company_46038d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["created_at"], name="ai_service__created_67de01_idx"
            ),
        ),
    ]
