# Generated by Django 4.2.7 on 2025-08-02 15:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "ai_service",
            "0003_lead_aiinsights_lead_ai_service__user_id_c89d44_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Opportunity name/title", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed opportunity description"
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated deal value",
                        max_digits=12,
                    ),
                ),
                (
                    "probability",
                    models.FloatField(help_text="Win probability percentage (0-100)"),
                ),
                (
                    "expected_close_date",
                    models.DateField(help_text="Expected close date"),
                ),
                (
                    "sales_cycle_days",
                    models.IntegerField(
                        blank=True, help_text="Predicted sales cycle in days", null=True
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospecting"),
                            ("qualification", "Qualification"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        default="prospecting",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "crm_record_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in external CRM system",
                        max_length=255,
                    ),
                ),
                (
                    "crm_system",
                    models.CharField(
                        blank=True,
                        help_text="Which CRM system this syncs with",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="ai_service.lead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="aiinsights",
            name="conversion_readiness_factors",
            field=models.JSONField(
                default=list, help_text="Factors indicating conversion readiness"
            ),
        ),
        migrations.AddField(
            model_name="aiinsights",
            name="opportunity_conversion_score",
            field=models.FloatField(
                default=0.0, help_text="Lead-to-opportunity conversion score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="aiinsights",
            name="recommended_for_conversion",
            field=models.BooleanField(
                default=False, help_text="AI recommends converting to opportunity"
            ),
        ),
        migrations.CreateModel(
            name="OpportunityIntelligence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversion_probability",
                    models.FloatField(
                        help_text="AI-calculated conversion probability (0-100)"
                    ),
                ),
                (
                    "conversion_likelihood",
                    models.CharField(
                        choices=[
                            ("very_high", "Very High (80-100%)"),
                            ("high", "High (60-79%)"),
                            ("medium", "Medium (40-59%)"),
                            ("low", "Low (20-39%)"),
                            ("very_low", "Very Low (0-19%)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "conversion_confidence",
                    models.FloatField(
                        help_text="Confidence in conversion prediction (0-100)"
                    ),
                ),
                (
                    "predicted_deal_size_min",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum predicted deal size",
                        max_digits=12,
                    ),
                ),
                (
                    "predicted_deal_size_max",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum predicted deal size",
                        max_digits=12,
                    ),
                ),
                (
                    "predicted_close_date",
                    models.DateField(help_text="AI-predicted close date"),
                ),
                (
                    "sales_cycle_prediction_days",
                    models.IntegerField(
                        help_text="Predicted sales cycle duration in days"
                    ),
                ),
                (
                    "recommended_stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospecting"),
                            ("qualification", "Qualification"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        help_text="AI-recommended current stage",
                        max_length=20,
                    ),
                ),
                (
                    "next_stage_probability",
                    models.FloatField(
                        help_text="Probability of advancing to next stage (0-100)"
                    ),
                ),
                (
                    "stage_advancement_timeline",
                    models.CharField(
                        help_text="Predicted timeline to advance stages", max_length=100
                    ),
                ),
                (
                    "overall_risk_level",
                    models.CharField(
                        choices=[
                            ("high", "High Risk"),
                            ("medium", "Medium Risk"),
                            ("low", "Low Risk"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(default=list, help_text="Identified risk factors"),
                ),
                (
                    "risk_mitigation_strategies",
                    models.JSONField(
                        default=list, help_text="Suggested risk mitigation strategies"
                    ),
                ),
                (
                    "competitive_threats",
                    models.JSONField(
                        default=list, help_text="Identified competitive threats"
                    ),
                ),
                (
                    "competitive_advantages",
                    models.JSONField(
                        default=list,
                        help_text="Our competitive advantages for this deal",
                    ),
                ),
                (
                    "win_strategy",
                    models.TextField(
                        blank=True, help_text="AI-recommended win strategy"
                    ),
                ),
                (
                    "similar_deals_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of similar historical deals analyzed",
                    ),
                ),
                (
                    "historical_win_rate",
                    models.FloatField(
                        blank=True, help_text="Win rate for similar deals", null=True
                    ),
                ),
                (
                    "benchmark_metrics",
                    models.JSONField(
                        default=dict, help_text="Benchmark metrics from similar deals"
                    ),
                ),
                (
                    "priority_actions",
                    models.JSONField(
                        default=list, help_text="High-priority recommended actions"
                    ),
                ),
                (
                    "next_best_actions",
                    models.JSONField(
                        default=list, help_text="Sequence of recommended next actions"
                    ),
                ),
                (
                    "resource_requirements",
                    models.JSONField(
                        default=list, help_text="Required resources and support"
                    ),
                ),
                ("last_analyzed", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence",
                        to="ai_service.opportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Intelligence",
                "verbose_name_plural": "Opportunity Intelligence",
                "ordering": ["-last_analyzed"],
            },
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["user", "stage"], name="ai_service__user_id_ddff07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["expected_close_date"], name="ai_service__expecte_bd89f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["probability"], name="ai_service__probabi_509edf_idx"
            ),
        ),
    ]
