# Generated by Django 4.2.7 on 2025-08-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_service",
            "0004_opportunity_aiinsights_conversion_readiness_factors_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunityintelligence",
            name="opportunity",
        ),
        migrations.DeleteModel(
            name="Opportunity",
        ),
        migrations.DeleteModel(
            name="OpportunityIntelligence",
        ),
    ]
