# Generated by Django 5.2.4 on 2025-08-01 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('failed', 'Failed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('caller_id', models.CharField(blank=True, max_length=50)),
                ('call_duration', models.DurationField(blank=True, null=True)),
                ('audio_quality_score', models.FloatField(blank=True, null=True)),
                ('conversation_context', models.JSONField(default=dict)),
                ('session_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('chunk_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('audio_data', models.BinaryField()),
                ('audio_format', models.CharField(default='wav', max_length=20)),
                ('sample_rate', models.IntegerField(default=16000)),
                ('duration_ms', models.IntegerField()),
                ('is_processed', models.BooleanField(default=False)),
                ('transcription', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_chunks', to='voice_service.callsession')),
            ],
            options={
                'ordering': ['chunk_number'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('turn_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speaker', models.CharField(choices=[('user', 'User'), ('nia', 'NIA')], max_length=10)),
                ('content', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('extracted_entities', models.JSONField(default=dict)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_turns', to='voice_service.callsession')),
            ],
            options={
                'ordering': ['turn_number'],
            },
        ),
        migrations.CreateModel(
            name='VoiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(default='en-US', max_length=10)),
                ('enable_automatic_punctuation', models.BooleanField(default=True)),
                ('enable_word_time_offsets', models.BooleanField(default=True)),
                ('speech_contexts', models.JSONField(default=list)),
                ('voice_name', models.CharField(default='en-US-Wavenet-D', max_length=50)),
                ('speaking_rate', models.FloatField(default=1.0)),
                ('pitch', models.FloatField(default=0.0)),
                ('volume_gain_db', models.FloatField(default=0.0)),
                ('auto_answer', models.BooleanField(default=True)),
                ('max_call_duration_minutes', models.IntegerField(default=30)),
                ('silence_timeout_seconds', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['user', 'status'], name='voice_servi_user_id_1776eb_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['start_time'], name='voice_servi_start_t_6d9c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='audiochunk',
            index=models.Index(fields=['session', 'chunk_number'], name='voice_servi_session_4bb395_idx'),
        ),
        migrations.AddIndex(
            model_name='audiochunk',
            index=models.Index(fields=['is_processed'], name='voice_servi_is_proc_1c76d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='audiochunk',
            unique_together={('session', 'chunk_number')},
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['session', 'turn_number'], name='voice_servi_session_69d881_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['speaker'], name='voice_servi_speaker_1cf622_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationturn',
            unique_together={('session', 'turn_number')},
        ),
    ]
