# Generated by Django 4.2.7 on 2025-08-04 17:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voice_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatBotCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=50, unique=True)),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("schedule_call", "Schedule Call"),
                            ("get_lead_info", "Get Lead Info"),
                            ("create_lead", "Create Lead"),
                            ("update_lead", "Update Lead"),
                            ("search_leads", "Search Leads"),
                            ("get_analytics", "Get Analytics"),
                            ("voice_transition", "Transition to Voice"),
                            ("help", "Help"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("usage_example", models.TextField()),
                ("parameters", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["command"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("voice_transition", "Transitioning to Voice"),
                            ("voice_active", "Voice Call Active"),
                            ("ended", "Ended"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("voice_transition_requested", models.BooleanField(default=False)),
                ("voice_transition_time", models.DateTimeField(blank=True, null=True)),
                ("participant_count", models.PositiveIntegerField(default=1)),
                ("is_group_chat", models.BooleanField(default=False)),
                ("chat_context", models.JSONField(default=dict)),
                ("user_available_for_voice", models.BooleanField(default=False)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("typing_indicator_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voice_session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_session",
                        to="voice_service.callsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ChatSearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("searchable_content", models.TextField()),
                ("conversation_summary", models.TextField(blank=True)),
                ("lead_information", models.JSONField(default=dict)),
                ("action_items", models.JSONField(default=list)),
                ("decisions_made", models.JSONField(default=list)),
                ("search_vector", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to="voice_service.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("message_number", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("nia", "NIA"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("file", "File Attachment"),
                            ("image", "Image"),
                            ("voice_note", "Voice Note"),
                            ("system", "System Message"),
                            ("bot_command", "Bot Command"),
                            ("screen_share", "Screen Share"),
                            ("lead_info", "Lead Information"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("attachments", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("extracted_entities", models.JSONField(default=dict)),
                ("intent", models.CharField(blank=True, max_length=100)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("thread_id", models.UUIDField(blank=True, null=True)),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voice_service.chatmessage",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="voice_service.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["message_number"],
            },
        ),
        migrations.CreateModel(
            name="ChatFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("archive", "Archive"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_status", models.CharField(blank=True, max_length=50)),
                ("extracted_text", models.TextField(blank=True)),
                ("is_safe", models.BooleanField(default=True)),
                ("scan_results", models.JSONField(default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="voice_service.chatmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_messages", models.PositiveIntegerField(default=0)),
                ("user_messages", models.PositiveIntegerField(default=0)),
                ("nia_messages", models.PositiveIntegerField(default=0)),
                ("average_response_time", models.FloatField(blank=True, null=True)),
                ("session_duration", models.DurationField(blank=True, null=True)),
                ("user_engagement_score", models.FloatField(default=0.0)),
                ("conversation_quality_score", models.FloatField(default=0.0)),
                ("topics_discussed", models.JSONField(default=list)),
                ("sentiment_analysis", models.JSONField(default=dict)),
                ("key_phrases", models.JSONField(default=list)),
                ("voice_transition_requested", models.BooleanField(default=False)),
                ("voice_transition_successful", models.BooleanField(default=False)),
                (
                    "voice_transition_reason",
                    models.CharField(blank=True, max_length=100),
                ),
                ("leads_discussed", models.PositiveIntegerField(default=0)),
                ("leads_created", models.PositiveIntegerField(default=0)),
                ("opportunities_identified", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="voice_service.chatsession",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "status"], name="voice_servi_user_id_4aa6da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["start_time"], name="voice_servi_start_t_ec4c48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["last_activity"], name="voice_servi_last_ac_3737b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsearchhistory",
            index=models.Index(
                fields=["user", "created_at"], name="voice_servi_user_id_47e656_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsearchhistory",
            index=models.Index(
                fields=["session"], name="voice_servi_session_b77fde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "message_number"],
                name="voice_servi_session_d10a30_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["sender"], name="voice_servi_sender_aafd4f_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["timestamp"], name="voice_servi_timesta_240446_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["status"], name="voice_servi_status_2873eb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="chatmessage",
            unique_together={("session", "message_number")},
        ),
        migrations.AddIndex(
            model_name="chatfile",
            index=models.Index(
                fields=["message"], name="voice_servi_message_ab0a1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatfile",
            index=models.Index(
                fields=["file_type"], name="voice_servi_file_ty_c156b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatfile",
            index=models.Index(
                fields=["is_processed"], name="voice_servi_is_proc_9b9ce3_idx"
            ),
        ),
    ]
